### PR TITLE
remove duplicate phrase

### PR DESCRIPTION
**Pull request by ghost**
This removes a small section of duplicate code. There should be no modification to functionality.

### CODE REVIEW

**Review by jimlambrt — APPROVED** [review]
LGTM.  I hope all is well @Peter-Tanski-Bose!

**Comment by ghost** [comment]
Thanks, @jimlambrt ! Glad to see you!

**Review by Ryan-Rose-Bose — APPROVED** [review]
💯

**Review by Alex-Grant-Bose — APPROVED** [review]
LGTM

**Pull request merged**
